project:
  type: website
  output-dir: docs

website:
  site-url: matthewbjane.com
  page-footer: 
    left: ""
  title: "Matthew B. Jané"
  favicon: webLogoFavicon2.png
  twitter-card: 
    image: webLogo2.png
  navbar:
    right: 
      - icon: github
        href: https://www.github.io/MatthewBJane
      - icon: twitter
        href: https://www.twitter.com/MatthewBJane
    logo: webLogoFavicon2.png
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Meta-Analysis Tricks
      - href: CV.qmd
        text: CV
      - href: Software.qmd
        text: Software
      - href: ArtifactCorrections.qmd
        text: Artifact Corrections

format:
  html:
    theme: 
      - darkly
      - barbie.scss
    css: styles.css
    toc: true

editor: visual

