---
format:
  html:
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css?family=Asap" type="text/css"/>
    toc: true
  pdf:
    pdf-engine: lualatex
    documentclass: scrartcl
    mainfont: Times New Roman
    monofont: Times New Roman
    sansfont: Times New Roman
    keep-tex: true
    urlcolor: Black
format-links: [pdf]

mainfont: Asap
sansfont: Asap
---

# Matthew B. Jané

::: {.content-visible when-format="pdf"}
{{< fa globe >}} [MatthewBJane.com](https://www.matthewbjane.com) \| {{< fa envelope >}} [matthew.jane\@uconn.edu](mailto:matthew.jane@uconn.edu) \| {{< fa brands twitter >}} [\@MatthewBJane](https://www.twitter.com/MatthewBJane) \| {{< fa brands github >}} [MatthewBJane](https://www.github.io/MatthewBJane)
:::

::: {.content-visible when-format="html"}
[{{< fa globe >}} Website](https://www.matthewbjane.com){.btn .btn-primary .btn-sm role="button" data-toggle="data" title="Data File"} [{{< fa envelope >}} Email](mailto:matthew.jane@uconn.edu){.btn .btn-primary .btn-sm role="button" data-toggle="data" title="Data File"} [{{< fa brands twitter >}} Twitter](https://www.twitter.com/MatthewBJane){.btn .btn-primary .btn-sm role="button" data-toggle="data" title="Data File"} [{{< fa brands github >}} Github](https://www.github.io/MatthewBJane){.btn .btn-primary .btn-sm role="button" data-toggle="data" title="Data File"}
:::

## <i class="fa-solid fa-user"></i> Bio

Current PhD student interested in developing statistical methods and software for meta-analyses and primary studies. Specifically, my current research projects focus on correcting bias in effect size estimates caused by statistical artifacts (see my open-access textbook on the topic at [matthewbjane.quarto.pub](https://matthewbjane.quarto.pub)). I am affiliated with the Systematic Health Action Research Program (SHARP) at the University of Connecticut where I am advised by Dr. Blair T. Johnson. I am also on the editorial board for *Psychological Bulletin* as a methodological reviewer.

## <i class="fa-solid fa-graduation-cap"></i> Education

-   2022--Present \| **Ph.D.** *Quantitative Psychology*, University of Connecticut, Storrs, Connecticut

    -   Research involves developing statistical methods and software for meta-analysis and evidence synthesis. Primarily focusing on correcting bias in effect size estimates induced by statistical artifacts.

-   2021--2022 \| **M.S.** *Behavioral Neuroscience*, University of Connecticut, Storrs, Connecticut

-   2018--2020 \| **B.S.** *Computational Neuroscience*, University of Connecticut, Storrs, Connecticut

## <i class="fa-solid fa-book"></i> Textbooks

- Jané, Matthew B. (2023) **Artifact Corrections for Effect Sizes: Applications Meta-Analysis and Implementation in R**, *by Matthew B. Jané*. An open-source book for correcting bias in effect size estimates contaminated by statistical artifacts. [https://matthewbjane.quarto.pub/artifact-corrections-for-effect-sizes/](https://matthewbjane.quarto.pub/artifact-corrections-for-effect-sizes/)

- Jané, M. B., Xiao, Q., Yeung, S. K., Caldwell, A. R., Dunleavy, D. J., ... (2023) **Guide to Effect Sizes and Confidence Intervals**, *by Matthew B. Jané*. A collaborative guide to calculating, interpreting, and reporting effect sizes and confidence intervals. Contains examples in R. [https://matthewbjane.quarto.pub/effect-size-and-confidence-intervals-guide/](https://matthewbjane.quarto.pub/effect-size-and-confidence-intervals-guide/)

## <i class="fa-solid fa-code"></i> Software

-   [<i class="fa-solid fa-cube"></i> R Package]{.badge .rounded-pill .bg-primary} **ThemePark**, Generating popular culture styled ggplot themes. [github.com/MatthewBJane/theme_park](https://github.com/MatthewBJane/theme_park). Featured on [rweekly.org](https://rweekly.org/2023-W32.html) and [flowingdata.com](https://flowingdata.com/2023/07/28/barbie-and-oppenheimer-themes-for-charts-in-r/)

-   [<i class="fa-solid fa-cube"></i> R Package]{.badge .rounded-pill .bg-primary} **POSC** An R Package for generating Probability of Outcome Superiority Curves (POSCs). [github.com/MatthewBJane/ThemePark](https://github.com/MatthewBJane/ThemePark)

-   [<i class="fa-solid fa-database"></i> Database]{.badge .rounded-pill .bg-primary} **OpenSynthesis**, website cataloging publicly available meta-analytic databases. [matthewbjane.com/opensynthesis](https://matthewbjane.com/opensynthesis)

-   [<i class="fa-solid fa-diagram-project"></i> Shiny App]{.badge .rounded-pill .bg-primary} **Artifact Simulator**, A Shiny App for Visualizing Statistical Artifacts. [matthewbjane.shinyapps.io/effect_size_artifact_bias](matthewbjane.shinyapps.io/effect_size_artifact_bias)

-   [<i class="fa-solid fa-globe"></i> Webpage]{.badge .rounded-pill .bg-primary} **Artifact Corrections for Effect Sizes**, A webpage documenting equations and code for effect size artifact corrections. [matthewbjane.com/ArtifactCorrections](matthewbjane.com/ArtifactCorrections)

-   [<i class="fa-solid fa-chart-simple"></i> Project Data & Code]{.badge .rounded-pill .bg-primary} **Primary Study Data and Code**, Repository of data and code for all primary study projects. <https://github.com/MatthewBJane/primary-project-data-code>.

-   [<i class="fa-solid fa-chart-simple"></i> Project Data & Code]{.badge .rounded-pill .bg-primary} **Meta-Analysis Data and Code**, Repository of data and code for all meta-analytic projects. <https://github.com/MatthewBJane/meta-analysis-project-data-code>.

## <i class="fa-solid fa-file-lines"></i> Publications

Johnson, B. T., **Jané, M. B.**, Curley, C. (2023). Methodological Quality in Research in Health Psychology. *Under review at Sage Journal of Health Psychology.*

::: {.content-visible when-format="html"}
::: {.btn-group role="group" aria-label="Open Science Links"}
[Data](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="data" title="data"} [Code](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="code" title="Data File"} [PDF](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="pdf" title="Data File"} [OSF](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="osf" title="Data File"}
:::
:::

<hr width="10%">

**Jané, M. B.**, Johnson, B. T. (2023). Correcting for Measurement Error in Repeated Measures Standardized Mean Differences. *Manuscript in Preparation.*

::: {.content-visible when-format="html"}
::: {.btn-group role="group" aria-label="Open Science Links"}
[Data](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="data" title="data"} [Code](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="code" title="Data File"} [PDF](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="pdf" title="Data File"} [OSF](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="osf" title="Data File"}
:::
:::

<hr width="10%">

Champion, G., **Jané, M. B.**, Johnson, B. T., and colleagues (2023). Efficacy of Mindfulness Based Stress Reduction Interventions on Anxiety and Depression in the United States: A Meta-Analysis. *Data being collected.*

::: {.content-visible when-format="html"}
::: {.btn-group role="group" aria-label="Open Science Links"}
[Data](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="data" title="data"} [Code](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="code" title="Data File"} [PDF](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="pdf" title="Data File"} [OSF](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="osf" title="Data File"}
:::
:::

<hr width="10%">

Harlow\*, T. J., **Jané\*, M. B.**, Read, H. L., & Chrobak, J. J. (2023). Memory retention following acoustic stimulation in slow-wave sleep: a meta-analytic review of replicability and measurement quality. *Frontiers in Sleep.*

::: {.content-visible when-format="html"}
::: {.btn-group role="group" aria-label="Open Science Links"}
[Data](https://github.com/MatthewBJane/meta-analysis-data-code/tree/main/acoustic_stimulation_and_memory/data){.btn-sm .btn .btn-primary role="button" data-toggle="data" title="data"} [Code](https://github.com/MatthewBJane/meta-analysis-data-code/tree/main/acoustic_stimulation_and_memory/analysis){.btn-sm .btn .btn-primary role="button" data-toggle="code" title="Data File"} [PDF](manuscripts/Harlow2023_Frontiers.pdf){.btn-sm .btn .btn-primary role="button" data-toggle="pdf" title="Data File"} [OSF](https://osf.io/8b49k/){.btn-sm .btn .btn-primary role="button" data-toggle="osf" title="Data File"}
:::
:::

<hr width="10%">

**Jané, M. B.**, Pisupati, S., Smith, K. E., Castro-Tonelli, L., Melo-Thomas, L., Schwarting, R. K., ... & Read, H. L. (2022). Correlations across timing cues in natural vocalizations predict biases in judging synthetic sound burst durations. *bioRxiv.*

::: {.content-visible when-format="html"}
::: {.btn-group role="group" aria-label="Open Science Links"}
[Data](https://doi.org/10.24433/CO.8495056.v1){.btn-sm .btn .btn-primary role="button" data-toggle="data" title="data"} [Code](https://doi.org/10.24433/CO.8495056.v1){.btn-sm .btn .btn-primary role="button" data-toggle="code" title="Data File"} [PDF](manuscripts/Jane2022_BioArxiv.pdf){.btn-sm .btn .btn-primary role="button" data-toggle="pdf" title="Data File"} [OSF](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="osf" title="Data File"}
:::
:::

<hr width="10%">

**Jané, M. B.**, Harlow, T. J., Martinez-Berman, L., Johnson, B. T. (2023). Cognitive Ability Moderates the Accuracy of Self-Reported Perfect Pitch. *Manuscript in Preparation.*

::: {.content-visible when-format="html"}
::: {.btn-group role="group" aria-label="Open Science Links"}
[Data](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="data" title="data"} [Code](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="code" title="Data File"} [PDF](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="pdf" title="Data File"} [OSF](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="osf" title="Data File"}
:::
:::

<hr width="10%">

**Jané, M. B.**, Harlow, T. J., Johnson, B. T. (2023). Temporal and Non-Temporal Sensory Discrimination and Fluid Intelligence: Artifact Correction Meta-Analysis. *Manuscript in preparation.*

::: {.content-visible when-format="html"}
::: {.btn-group role="group" aria-label="Open Science Links"}
[Data](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="data" title="data"} [Code](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="code" title="Data File"} [PDF](){.btn-sm .btn .btn-primary .disabled role="button" data-toggle="pdf" title="Data File"} [OSF](https://osf.io/d6yxf/){.btn-sm .btn .btn-primary role="button" data-toggle="osf" title="Data File"}
:::
:::

<hr width="10%">


<script data-name="BMC-Widget" data-cfasync="false" src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" data-id="matthewbjane" data-description="Support me on Buy me a coffee!" data-message="" data-color="#f1f9fa" data-position="Right" data-x_margin="18" data-y_margin="18"></script>
