---
title: Memory retention following acoustic stimulation in slow-wave sleep a meta-analytic review of replicability and measurement quality
author:
  - name: Tylor J. Harlow
  - name: Matthew B. Jané
  - name: Heather L. Read
  - name: James J. Chrobak
abstract: hello
---

**Jané, M. B.**, Johnson B. T. (2023). Correcting for Measurement Error in Repeated Measures Standardized Mean Differences. Manuscript in Preparation.

Harlow\*, T. J., **Jané\*, M. B.**, Read, H. L., & Chrobak, J. J. (2023). Memory retention following acoustic stimulation in slow-wave sleep: a meta-analytic review of replicability and measurement quality. Frontiers in Sleep.

**Jané, M. B.**, Pisupati, S., Smith, K. E., Castro-Tonelli, L., Melo-Thomas, L., Schwarting, R. K., ... & Read, H. L. (2022). Correlations across timing cues in natural vocalizations predict biases in judging synthetic sound burst durations. bioRxiv.

::: {.content-visible when-format="html"}
[Data](https://codeocean.com/capsule/8495056/tree){.btn .btn-outline-success .btn-sm role="button" data-toggle="data" title="Data File"} [Code](https://codeocean.com/capsule/8495056/tree){.btn .btn-outline-success .btn-sm role="button" data-toggle="code" title="Analysis Code"} [PDF](manuscripts/Jane2022_BioArxiv.pdf){.btn .btn-outline-success .btn-sm role="button" data-toggle="pdf" title="PDF of Manuscript"}
:::
